### PR TITLE
bug fixes to readPC.R, delintPC.R

### PR DESCRIPTION
**Pull request by mkclapp**
I pushed these changes from the wrong branch, but they do the following:

**readPC.R:**
-removes the code that creates a .csv filename that depends on sys.Date(). 
-ran styler on the entire file

**delintPC.R**:
-set visit limit to 3 visits (not 4) to reduce 0s in the data
-removed the filter that takes out point 1072 from the data frame (was previously filtered out bc an old version of the veg data did not contain info for that point... that issue has apparently been resolved in the up-to-date version of veg data on this repository, so adding it back in)
-ran styler on the entire file

### CODE REVIEW

**Review by ddkapan — APPROVED** [review]
These all look fine, the only issue may be that we would want to handpick the visits if we have a greater than three to choose from. This may be accomplished by removing visits from people who did fewer point counts overall. If you think this is a useful idea let's make a new issue for it.

**Comment by ddkapan** [comment]
One more thing before I delete the branch. What do you mean you made these changes from the wrong branch? Are you happy with the changes?

**Comment by mkclapp** [comment]
> One more thing before I delete the branch. What do you mean you made these changes from the wrong branch? Are you happy with the changes?

I meant to create a new branch with a name specific to the issue. The current branch I was working on refers to adding PC models, not debugging the readPC and delintPC files. I'll keep the branch open because I have other edits that actually *do* belong on that branch name (additions/edits to the models themselves).

Thanks!

**Comment by mkclapp** [comment]
> These all look fine, the only issue may be that we would want to handpick the visits if we have a greater than three to choose from. This may be accomplished by removing visits from people who did fewer point counts overall. If you think this is a useful idea let's make a new issue for it.

This is a good idea and something we should implement; +1 to create new issue!

**Pull request merged**
