### PR TITLE
Automated code formatting (proposal and base application)

### PR DESCRIPTION
**Pull request by matth79**
Feel free to summarily reject this PR if you don't agree. It is polite proposal / demo, no semblance of a hard sell is intended:

A convention of always formatting .R sources with ```styler``` before committing them

The commit documents the rationale in DEVELOPING.md.

While there are many diff lines, they are all automated, as one could verify by running style_dir() in a local branch and "git diff"'ing that branch with this one.

### CODE REVIEW

**Comment by matth79** [comment]
If for some reason this breaks something, ```git revert``` can undo it, and I will help with any complications.

**Review by ddkapan — COMMENTED** [review]
This is really intriguing.  I'm generally a fan of everything tidyverse. Since we are using different development platforms, this is nice to run the style checks programmatically.  The only thing that is a bit annoying is having to type extra spaces ... but since there is an R-studio plugin that won't be much of an issue.  I'd like to hear from @jdumbacher and @mkclapp and @mschulist to see what they think, but I like it! :)

**Comment by mschulist** [comment]
I love the tidyverse styler. It makes everything look so neat and fixes spaces that I forget to put in. I'm all for using the styler!

**Comment by ddkapan** [comment]
@mkclapp & @jdumbacher please review fyi and feel free to approve pull request!

**Comment by jdumbacher** [comment]
Yes - thanks for suggesting this Matt!  This looks fine (and a good idea in general).  I've looked over changes and all look good or at least benign, and help with reading and formatting.  I will have to learn to use the styler before my commits in the future!!!  Cheers!

**Review by mkclapp — APPROVED** [review]
Strong support for styler! Thanks for the suggestion @matth79 !

**Comment by ddkapan** [comment]
Great resolution to conflicts!

**Pull request merged**
