### PR TITLE
readml API

### PR DESCRIPTION
**Pull request by matth79**
(no rush to review)

This PR is request for comment on the API for reading ML outputs and restructuring them for JAGS. Let me know if anything looks, e.g.: missing, wrong, unclear, hard-to-use...

If all looks OK, my plan is to make a separate PR for the implementation.

### CODE REVIEW

**Review by ddkapan — COMMENTED** [review]
This is perfect. You already have your filters drafted from the jupyter notebook.  The 'default' visits is logical but probably in the future will be 10 minutes (to compare directly across PC and ARU time stamps but if any arbitrary time/aggregation is handled file is fine. I assume you'll finish the functions then finalize the pull request or should I approve and you make a new PR for the final product?

**Comment by ddkapan** [comment]
@mschulist is rotating the large input on our big machines using microbenchmark to figure out costs (ram, time).  I suggested we investigate efficiencies available from packages already written, including data.table, @matth79 can you advise if it would help to use [setkey](https://search.r-project.org/CRAN/refmans/data.table/html/setkey.html)?

**Comment by matth79** [comment]
## PRs

I was planning to do the implementation in a separate PR, or two, since @mkclapp and I had discussed a staged approach:

1. Inferface definition (this PR)
2. Placeholder implementation that reads from dataML_model.csv (and thus only supports RBNU 2020).
3. Migrate combined.R to use (2).
4. Full implementation that reads the new CSV @mschulist is working on.

Doing all of these as separate PRs would again me a nod to [small CLs](https://google.github.io/eng-practices/review/developer/small-cls.html). It's possible to go over the top with that, but usually more, smaller reviews are easier.

## Aggregation

10 minutes to be directly comparable to point count is a good thing to identify early. I wasn't planning to implement "any/arbitrary time" but rather a discrete set of "strategies" identified by string. One strategy could be "into buckets of fixed duration" where the duration could be a parameter. There's a little ambiguity left in that because of the duty cycle. For example, (F1 11:00-15:00 concat F2 00:00-00:06) is different in kind from (F3 03:00-13:00). But since lambda and omega are rates / 15 min, is it fair to just say we can linearly scale them by (2 / 3) to get rates / 10 min?

## setkey

I can speculate on efficiency, knowing it's risky business doing that with no benchmarks. There are two sides:

- Reader side (this library): the CSV file doesn't know if setkey has been / will be called. However, if the rows of the CSV file(s) are known to be globally ordered by (species, time), which is the assertion being made by setkey, then slicing and grouping by those dimensions ought to be a lot more efficient (finding endpoint indices by binary search rather than needing to do a full scan).
- Writer side:
  - It's not so obvious where setkey plays a role. I think the raw input CSV rows are already sorted by time. Inside that is nested an (implicit?) inner ordering by species, the order of the columns. If I'm right in assuming single- and few-species models will be the common cast for a while, we'll want slicing out a single species to be efficient (on the reader side), which has implications for how the writer sorts and/or partitions its output. (See "globally ordered" above.)
  - The separate files {species}_{year}.csv suggested in the design doc (partitioning) are about as efficient as you can get for slicing by single species. However, since I wrote that suggestion, I have become more OK with the idea that we can
    - omit all rows from the tall table where logit < -2.5, which cuts total tall table size down to 500MB.
    - at which point separate files per partition, while still more performant, seems overkill
  - The optimal algorithm, though unusual in R, is a streaming read of the CSV with a nested loop over rows and fields. Running time is linear in raw input size. It can be parallelized by splitting time ranges, but let's not cover that extension.
```
input: wide CSV sorted by time csv,
       per-species open CSV writiers writers

for each row in csv:
  for each species, logit in logit_columns(row):
    writers[species].write((point(row), time(row), logit))


# If single-file output is desired:

input: per-species open CSV readers readers,
       concatenated CSV writer writer

for each reader in readers:
  copy(reader, writer)
```

**Comment by ddkapan** [comment]
Ok small CL agreed!

**Pull request merged**
