### PR TITLE
Library for running JAGS over all species in parallel

### PR DESCRIPTION
**Pull request by matt-har-vey**
I am proposing to merge this into main with minimal changes to the model currently in main.

When we eventually settle on the preferred form of the default model, then we can merge that into combined.R with the small changes needed to adapt it to the funtion(params) API.

Reviewers: please try your own test run and say whether it works or give feedback on the API.

When reading the code, I suggest setting the UI to ignore whitespace differences when looking at the diff.

### CODE REVIEW

**Comment by mschulist** [comment]
That looks great! I think it might be worth looking into the specific model used, as I believe that the model in this PR is not the "latest and greatest." But changing the model should not be too difficult. Also, certain models use top1 instead of all of the data, so we might want to add the ability to change which csv the `model_read_lib.R` uses (that would also make it faster because reading top1 is much faster than the entire dataset).

**Comment by matt-har-vey** [comment]
Thanks for looking Mark.

On model selection, the design criterion I adopted here is "separation of concerns." Specifically, (A) define the model, (B) run the model with lots of different parameter settings, collect the results, and parallelize well.

In other words, this was designed to work for any "model," where "model" is just a function taking a params list and returning a jagsResult.

"changing the model shouldn't be too difficult" - yes. Any of the many copies of combined.R have been created could just make the analogous change to the one this has made in `combined.R`, i.e. wrap the model as a trialFn.

I totally agree with reworking `model_read_lib.R` to allow a parameter for selecting between top1 / top3 / threshold. I think R has some sort of categorical type, like what's called enum in other languages. (enum ScoreSpace { TOP_1, TOP_3, THRESHOLD }). Wouldn't it be great if the enum values could also take parameters (c++ std::variant, but I digress).

Then that scoreSpace could become a trial hyperparameter, like species and year are in this PR.

If we were looking for even more efficiency, both speed and memory, we could consider changing the signature of trialFns so that the data list from model_read_lib was also an argument (trialFn(params, fullData)). That way we wouldn't re-read separately for every trial, and it would be more RAM efficient when the executor is multiprocessing because that uses fork, and Linux fork is copy-on-write (shares RAM from the parent process until it changes). However, that would come at the cost of some rework and a breaking change to function signature of readCombined. It would add an extra step if trying to use readCombined independently of run_trials.R.

**Comment by mschulist** [comment]
Ok, that sounds good. 

> If we were looking for even more efficiency, both speed and memory, we could consider changing the signature of trialFns so that the data list from model_read_lib was also an argument (trialFn(params, fullData)). 

Regarding this change, I attempted to do this in the `combined-input-function` branch (with the amount of data, not species). If we make a list of length(nspecies) where each item in the list is a `jagsinput` for a different species, we can just loop through each of the items in the list as an input to the model function. It would still take a while to make the giant data_list, but we would not have to remake it every time we run the model (if we are running different models).

**Comment by mschulist** [comment]
Something like this 
```
data <- future_map(speciesCodes, 
              ~ readCombined(
                  species = c(.x),
                  years = c(2021),
                  beginTime = dhours(6),
                  endTime = dhours(10),
                  visitLimit = aruVisitLimit,
                  visitAggregation = "file",
                  thresholdOptions = list(
                    value = threshold,
                    is.quantile = F
                  ),
                  squeeze = T
))
```

Using furrr allows for it to run more quickly, but ideally this should only have to be run one time as `data` can be reused.

**Pull request merged**
