### PR TITLE
scratch_combined_model runnable from clean session

### PR DESCRIPTION
**Pull request by matth79**
* Reorders assignments to avoid any use before definition.
* Sorts library() statements alphabetically.
* Limits drive_sync to only strictly necessary folders
* Removes trailing whitespace

### CODE REVIEW

**Comment by ddkapan** [comment]
Nice changes, the only thing I was thinking was that it filtering should be in this script as the output of read + delint should be more generic for other downstream analyses. Onnto you @mkclapp ...

**Comment by matth79** [comment]
This is trying to be one of those [Small CLs](https://google.github.io/eng-practices/review/developer/small-cls.html#why) with the limited purpose of making this run end-to-end without errors by calling Rscript or source()'ing into a brand new session.

Therefore the rest is general discussion not strictly regarding this PR.
----
I agree with the filtering comment, but it sounds like material for opening a new issue.

* As I read [this line](https://github.com/calacademy-research/COMB/blob/f595e3fbc31bf11eeb3caef9b38e7f3ba52e4dba/models/src/scratch_combined_model.R#L33), the point counts are filtered by species and year.
* dataML_model, though, probably should be read here as all-species, all-year, and currently it is filtered upstream.

Beyond this one, I'm finding more:
* "Rhat values indicate convergence failure"
* jags code referring to y when it probably means yRBNU (or more generic name for point counts)
* unrealistic inferences, e.g. p_10 = 0.5.

My local edits are in flux, and when they stabilize, I'll open issues for those that could be interesting to the entire project, if someone else has not found them already.

**Comment by ddkapan** [comment]
Thanks, especially for the Change List (CL) suggestion. That's something we will all benefit from.

**Comment by ddkapan** [comment]
One last thing, since we have some requests stacking up since its a weekend (sorry) is their any problem merging them in chronological order? If not will do tomorrow once I can look them over on my large screens as opposed to my phone.

**Comment by matth79** [comment]
There's no hurry at all, especially on a weekend.

Chronological order is the least prone to cause merge conflicts. The styler branch probably will have some conflicts, though, and it's probably easier to leave it until last and merge main into styler before trying to merge styler into main.

**Comment by ddkapan** [comment]
Ok, I think everyone should have a chance to read through then I can merge oldest to newest with exception of styler which will be in your suggested order:
- main --> styler 
... then test and then
- styler --> main!

**Review by mkclapp — COMMENTED** [review]
The changes look good to me from here, but I haven't run them on my local machine because I'm not able to check out the fork that contains the modified script. Perhaps because the modifications are on your local fork, Matt, and not on a branch on COMB? 

I have restarted RStudio, pulled the repo, used the command 'git branch -a' to list all the branches, and "combined_script" does not exist as a branch for me to switch onto. The file in question "scratch_combined_model.R" currently on main does not reflect the changes you've made @matth79 . 

I have a hunch that my continuing issue with drive_sync() will prevent me from running the script cleanly anyway, but it would definitely be good to try. I have to sign off at 3p today but can get back to this first thing Tuesday.

**Review by ddkapan — APPROVED** [review]
I think this is great! Looked over every line, the devil will be in how it runs after all the other merges (pull requests) let's go!

**Pull request merged**
